// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8ptnPDpCbZdKNjCfQJ0SsbLiTl1HenuA',
    appId: '1:260492813683:web:42bab1ad634da9fcd99106',
    messagingSenderId: '260492813683',
    projectId: 'tikchat-874b7',
    authDomain: 'tikchat-874b7.firebaseapp.com',
    storageBucket: 'tikchat-874b7.appspot.com',
    measurementId: 'G-40L2MEMNM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqyR_EjfxXG2Xmgq1LeDCx53tbBkg0Wkc',
    appId: '1:260492813683:android:d180c831dba4130fd99106',
    messagingSenderId: '260492813683',
    projectId: 'tikchat-874b7',
    storageBucket: 'tikchat-874b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs04BsY7-Y-_QIlFY4jvRRbDckkv3jwL8',
    appId: '1:260492813683:ios:da0ce460eae64607d99106',
    messagingSenderId: '260492813683',
    projectId: 'tikchat-874b7',
    storageBucket: 'tikchat-874b7.appspot.com',
    iosClientId: '260492813683-vi5lbq1tsn9sef069fjl86vo3dqpgs8s.apps.googleusercontent.com',
    iosBundleId: 'com.tikkchat.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs04BsY7-Y-_QIlFY4jvRRbDckkv3jwL8',
    appId: '1:260492813683:ios:8a8bc269be4888c7d99106',
    messagingSenderId: '260492813683',
    projectId: 'tikchat-874b7',
    storageBucket: 'tikchat-874b7.appspot.com',
    iosClientId: '260492813683-rpc2j93eah87smunm49vjtr5hn0mbt87.apps.googleusercontent.com',
    iosBundleId: 'com.example.temoLive',
  );
}
